### PR TITLE
Implement SingleDelete

### PR DESCRIPTION
**Pull request by hueypark**
Informs #222.

In Pebble SingleDelete combined with Delete/Merge, it is converted to Delete. But, since SingleDelete is only suitable for special workloads, comment not mention it. If we commenting on them, someone will try to use that unusual behavior.

### CODE REVIEW

**Comment by ajkr** [comment]
> Requiring SINGLEDEL to cover exactly one SET and misbehaving badly when that requirement is violated (i.e. accumulating SINGLEDEL records at the bottom level) feels like poor API design.

This doesn't make sense to me. The whole SingleDelete optimization is to drop a SINGLEDEL when it encounters the SET it covers. What about if the SINGLEDEL covers two SETs? The outcome is non-deterministic (which IMO is a worse outcome than tombstone stuck in bottom level). What if the SINGLEDEL covers a MERGE or DELETE? According to this PR it transforms the SINGLEDEL into a DELETE even if it's writing to bottom level, which is the same bad behavior you're asking to avoid.

> Yeah, we're requiring the lot from the user to use SINGLEDEL correctly, but might as well prevent more badness when possible. Not allowing a RANGEDEL to lie between a SINGLEDEL and a SET further burdens the user. Perhaps I'm misjudging how much effort this will be.

I don't think I'm arguing for burdening the user. I'm arguing that if our requirement for SingleDelete is that it deletes "at most one key" rather than "exactly one key", we should clarify that and do all the work to make it happen. I do not understand how not half-supporting an explicitly unsupported use case (SINGLEDEL covering zero keys) is "poor API design".

**Comment by petermattis** [comment]
> > Requiring SINGLEDEL to cover exactly one SET and misbehaving badly when that requirement is violated (i.e. accumulating SINGLEDEL records at the bottom level) feels like poor API design.
> 
> This doesn't make sense to me. The whole SingleDelete optimization is to drop a SINGLEDEL when it encounters the SET it covers. What about if the SINGLEDEL covers two SETs? The outcome is non-deterministic (which IMO is a worse outcome than tombstone stuck in bottom level). What if the SINGLEDEL covers a MERGE or DELETE? According to this PR it transforms the SINGLEDEL into a DELETE even if it's writing to bottom level, which is the same bad behavior you're asking to avoid.

Heh, I suppose referring to good API design anywhere near SINGLEDEL is problematic as the API is fundamentally fragile.

Let me take a step back. I'd like to have SINGLEDEL provide reasonable behavior when possible. A SINGLEDEL covering two SETs is going to be non-deterministic as that is fundamental to the SINGLEDEL operation. But what about a SINGELDEL covering 0 records? Or one covering a MERGE or a DELETE? I think we can define reasonable semantics for all of these cases **and** I think those semantics are not onerous to implement. I don't believe we (CRDB) need those semantics, but I think we (Pebble) should implement something to cover those cases, whether it be a fatal error, a panic, or something.

The semantics I'm arguing for is that a SINGLEDEL acts like DEL except that when it is compacted with a SET (in the same snapshot stripe) it is elided from the output. A SINGLEDEL at the bottom level of the tree should be elided. SINGEDEL covering a MERGE/DELETE should be transformed into a DEL. My intuition is that implementing these semantics will be as much work as implementing and testing any other semantics (including crashing). 

> I don't think I'm arguing for burdening the user. I'm arguing that if our requirement for SingleDelete is that it deletes "at most one SET" rather than "exactly one SET", we should clarify that and do all the work to make it happen. 

Ack, I think we should clarify the semantics, and I think they should be "SingleDelete deletes at most one SET", though the phrasing on that is slightly problematic. SINGLEDEL might delete more that one SET (depending on the order of compactions). Perhaps, "SINGLEDEL can delete zero or one SET records. If there are two or more SET records (i.e. a record was overwritten), the behavior of SINGLEDEL is non-deterministic."

> We should consider whether general API misuse should cause the DB to go into read-only mode or crash, but that's separate from the question of whether SINGLEDEL covering zero SETs should be supported or not.

When possible I think we should provide guard rails. Crashing is reasonable in some cases, or returning an error. For example, Pebble returns an error if you close a DB with open iterators as this is indicative of an iterator leak. And operations on a closed DB return an error. Unfortunately, with SINGLEDEL there is a misuse (SINGLEDEL covering 2 or more SETs) which we can't efficiently detect.

**Comment by petermattis** [comment]
@hueypark Thanks again for the contribution. Apologies for all of the back and forth, but I think this ended up in a good place. I'm going to go ahead and merge this PR.

Heads up that I'm planning to move this repo to `github.com/cockroachdb/pebble` today.

**Comment by hueypark** [comment]
@petermattis @ajkr Thank again for your kind review on this PR.

And I want to contribute to CockroachDB in the long term. Assign me freely whenever there is an appropriate issue.

**Pull request merged**
