### PR TITLE
Manually inline decodeVarint

### PR DESCRIPTION
**Pull request by petermattis**
Decoding varints occurs multiple times in some of the inner-most code of
sstable seeking and iteration. Manually inlining the varint decoding
provides a significant speedup on both go1.11 and go1.12 (the numbers
below are for go1.11). Perhaps someday this won't be necessary, but
until then the perf win is worth grabbing.

```
name                          old time/op  new time/op  delta
BlockIterSeekGE/restart=16-8   488ns ± 1%   416ns ± 1%  -14.81%  (p=0.000 n=10+10)
BlockIterSeekLT/restart=16-8   531ns ± 1%   460ns ± 1%  -13.25%  (p=0.000 n=10+10)
BlockIterNext/restart=16-8    22.4ns ± 0%  18.1ns ± 1%  -19.42%  (p=0.000 n=6+10)
BlockIterPrev/restart=16-8    38.9ns ± 3%  32.1ns ± 2%  -17.52%  (p=0.000 n=10+9)
TableIterSeekGE/restart=16-8  1.32µs ± 0%  1.20µs ± 1%   -9.72%  (p=0.000 n=8+10)
TableIterSeekLT/restart=16-8  1.37µs ± 1%  1.24µs ± 0%   -9.50%  (p=0.000 n=9+10)
TableIterNext/restart=16-8    25.6ns ± 1%  20.8ns ± 3%  -18.58%  (p=0.000 n=10+10)
TableIterPrev/restart=16-8    40.8ns ± 2%  36.2ns ± 3%  -11.30%  (p=0.000 n=10+10)
```

### CODE REVIEW

**Comment by petermattis** [comment]
This change is [Reviewable](https://reviewable.io/reviews/petermattis/pebble/73)

**Comment by petermattis** [comment]
Added a few more commits with additional micro optimizations to `blockIter`. These micro optimizations add up. Here is the delta from before these changes (i.e. `master`):

```
name                          old time/op  new time/op  delta
BlockIterSeekGE/restart=16-8   487ns ± 1%   352ns ± 1%  -27.75%  (p=0.000 n=9+10)
BlockIterSeekLT/restart=16-8   538ns ± 2%   406ns ± 1%  -24.63%  (p=0.000 n=10+10)
BlockIterNext/restart=16-8    22.3ns ± 1%  12.7ns ± 0%  -43.35%  (p=0.000 n=10+9)
BlockIterPrev/restart=16-8    37.1ns ± 1%  27.8ns ± 3%  -25.11%  (p=0.000 n=10+10)
TableIterSeekGE/restart=16-8  1.33µs ± 1%  1.09µs ± 1%  -17.85%  (p=0.000 n=9+9)
TableIterSeekLT/restart=16-8  1.38µs ± 1%  1.15µs ± 1%  -16.46%  (p=0.000 n=10+8)
TableIterNext/restart=16-8    25.3ns ± 1%  16.0ns ± 1%  -36.95%  (p=0.000 n=9+10)
TableIterPrev/restart=16-8    42.1ns ± 3%  32.9ns ± 4%  -21.83%  (p=0.000 n=10+10)
```

**Comment by petermattis** [comment]
> I am surprised functions like DecodeInternalKey are not inlineable.

I'd guess it is just over whatever threshold of size the Go compiler uses as a heuristic.

> Hope our DB doesn't evolve into one giant function someday :).

Heh, I don't think that will happen. The inner loops like this are rare. I wish there was a slightly cleaner way to express that inlining should happen. I was even pondering adding a pre-processing step to accomplish this, but that seemed like overkill.

**Comment by jordanlewis** [comment]
Why do we use varints at all? Decoding varints is one of the most expensive things in the hot decode paths of CockroachDB. I don't know the context here, but could we consider replacing the use of varints in most places with fixed size integers?

**Comment by petermattis** [comment]
> Why do we use varints at all?

Because the sstable format that we want to be compatible with uses varints.

> Decoding varints is one of the most expensive things in the hot decode paths of CockroachDB. I don't know the context here, but could we consider replacing the use of varints in most places with fixed size integers?

I've experimented with both fixed size integers (`uint16`) and other varint encodings. Neither show any benefit over the inlining done here. The other varint encoding I experimented with can be significantly faster for multi-byte varints:

```
// xxxxxxx1  7 bits in 1 byte
// xxxxxx10 14 bits in 2 bytes
// xxxxx100 21 bits in 3 bytes
// xxxx1000 28 bits in 4 bytes
// xxx10000 35 bits in 5 bytes
```

The low-bits describe how full bytes follow. Benchmarking shows this is only a win when a varint needs 3 or more bytes to be encoded. For 1 and 2 byte varints the inlining done in this PR is either faster or the same speed.

**Pull request merged**
