### PR TITLE
Unbreak the build on freebsd

### PR DESCRIPTION
**Pull request by knz**
Needed for https://github.com/cockroachdb/cockroach/issues/39482

### CODE REVIEW

**Comment by petermattis** [comment]
This change is [Reviewable](https://reviewable.io/reviews/petermattis/pebble/216)

**Comment by knz** [comment]
> sorry for the hassle. 

no worries we're in this together

> I suppose I should add some cross builds to the CI.

meh. rocksdb doesn't test it either (otherwise they would have fixed the clang 8 breakage)

> Should this file be named preallocate_bsd.go. Seems bold to claim unix for the BSD systems, but perhaps there is some existing pattern you're following here.

Actually I hadn't done the homework properly. Now it's done. PTAL. Also please review the new commit message.

**Comment by knz** [comment]
please take it over.

**Comment by knz** [comment]
I see wisdom in doing the allocate/truncate early because it updates the filesystem metadata upfront. I suppose that it also verifies upfront whether an operation is going to run into a filesystem's limit on file size, and in some cases, storage capacity.

**Comment by petermattis** [comment]
> I see wisdom in doing the allocate/truncate early because it updates the filesystem metadata upfront. 

The preallocation is done in order to improve syncing performance. That was the theory. In practice it doesn't have much of an effect on Linux/ext4 because the metadata still has to be written on every sync which extends the file due to security considerations (the OS can never allow data from another file to be exposed). 

> I suppose that it also verifies upfront whether an operation is going to run into a filesystem's limit on file size, and in some cases, storage capacity.

Perhaps, yet that wasn't the motivation for preallocation in either RocksDB or Pebble.

**Comment by petermattis** [comment]
@knz Care to give #217 a rubber-stamp?

**Comment by petermattis** [comment]
Obsoleted by #217.

**Pull request closed without merging**
